version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
